networks:
  frontend:
  backend:
  proxy-network:
    external: true

volumes:
  pgdata:
  opdata:
  app_models:

services:
  db:
    image: postgres:13
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p4ssw0rd}
      POSTGRES_DB: openproject
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - frontend
      - proxy-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    command: |
      sh -c "
      echo 'server { listen 80; location / { proxy_pass http://web:8080; proxy_set_header Host $$host; proxy_set_header X-Real-IP $$remote_addr; proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $$scheme; } }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

  web:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: ./docker/prod/web
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
      - "${APP_MODELS:-app_models}:/app/app/models"
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - autoheal=true
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_INTERVAL: 30
    restart: unless-stopped

  worker:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: ./docker/prod/worker
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
      - "${APP_MODELS:-app_models}:/app/app/models"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"

  cron:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: ./docker/prod/cron
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
      - "${APP_MODELS:-app_models}:/app/app/models"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"

  seeder:
    image: openproject/openproject:${TAG:-16-slim}
    restart: on-failure
    command: ./docker/prod/seeder
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
      - "${APP_MODELS:-app_models}:/app/app/models"
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=openproject"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCOPE=openproject
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL:-}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER:-openproject-watchtower}
      - WATCHTOWER_NOTIFICATION_TEMPLATE=${WATCHTOWER_NOTIFICATION_TEMPLATE:-}
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
